#!/usr/bin/env python3
"""Generate the 12-cell production ablation matrix as YAML configs.

The thesis ablation has six masking strategies × two architectures
(per-time-step baseline + factorized space-time). To keep the source
of truth in one place — and to make hyperparameter changes a one-line
edit instead of a 12-file refactor — this script renders all 12
configs from a shared template.

Output goes to ``examples/config/ablation_case118/`` so the configs
are committed alongside the rest of the codebase but kept out of the
flat ``examples/config/*.yaml`` glob the auto-discovery test
exercises (those tests run on every pytest invocation; the production
configs are heavy and don't need that coverage).

Run this script whenever the production hyperparameters change:

    python examples/scripts/generate_ablation_configs.py

Then commit the regenerated files alongside any change to this script.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict

import yaml


# ---------------------------------------------------------------------------
# The ablation matrix — six masking strategies × two architectures.
# ---------------------------------------------------------------------------

MASKING_STRATEGIES: Dict[str, Dict[str, Any]] = {
    "random_point": {"strategy": "random_point", "rate": 0.5},
    "block_temporal": {
        "strategy": "block_temporal",
        "block_length": 4,
        "anchor": "random",
    },
    "causal": {"strategy": "causal", "anchor_position": "random"},
    "block_spatial": {"strategy": "block_spatial", "spatial_rate": 0.3},
    "tube": {"strategy": "tube", "tube_rate": 0.3, "tube_seed": 0},
    "topology": {
        "strategy": "topology",
        "hop_count": 2,
        "anchor_strategy": "random_bus",
    },
}

ARCHITECTURES: Dict[str, str] = {
    "baseline": "TemporalGNS_heterogeneous",
    "factorized": "FactorizedSpatioTemporalGNS_heterogeneous",
}


# ---------------------------------------------------------------------------
# Production hyperparameters — change here, run the script, commit.
# ---------------------------------------------------------------------------

PROD_HYPERPARAMS: Dict[str, Any] = {
    "callbacks": {"patience": 100, "tol": 0},
    "task": {"task_name": "TemporalReconstruction"},
    "data": {
        "baseMVA": 100,
        "mask_value": 0.0,
        "normalization": "HeteroDataMVANormalizer",
        "networks": ["case118_ieee"],
        "scenarios": [3000],
        "test_ratio": 0.1,
        "val_ratio": 0.1,
        "workers": 8,
        "split_by_load_scenario_idx": True,
        "window_size": 12,
        "window_stride": 1,
    },
    "model": {
        # `type` filled in per-architecture below.
        "attention_head": 4,
        "edge_dim": 10,
        "hidden_size": 48,
        "input_bus_dim": 15,
        "input_gen_dim": 6,
        "output_bus_dim": 2,
        "output_gen_dim": 1,
        "num_layers": 4,
        "dropout": 0.0,
    },
    "optimizer": {
        "beta1": 0.9,
        "beta2": 0.999,
        "learning_rate": 0.0005,
        "lr_decay": 0.7,
        "lr_patience": 5,
    },
    "seed": 0,  # overridden per run by the launcher.
    "training": {
        "batch_size": 32,
        "epochs": 30,
        "loss_weights": [1.0],
        "losses": ["MaskedBusMSE"],
        "loss_args": [{}],
        "accelerator": "auto",
        "devices": "auto",
        "strategy": "auto",
    },
    "verbose": True,
}


HEADER_COMMENT = (
    "# AUTO-GENERATED by examples/scripts/generate_ablation_configs.py.\n"
    "# Edit that script (or PROD_HYPERPARAMS in it) and re-run, do not\n"
    "# hand-edit this file — your changes will be overwritten on the\n"
    "# next regeneration.\n"
    "#\n"
    "# Architecture: {arch_label} ({arch_class})\n"
    "# Masking strategy: {strategy_name}\n"
    "# Data: 3000-scenario QSTS on case118_ieee, window_size=12, stride=1.\n"
    "# Training: 30 epochs, batch 32, hidden 48, num_layers 4,\n"
    "#           attention_head 4. Loss: MaskedBusMSE only.\n"
    "# Seed: overridden at launch time by the run-matrix script.\n"
)


def _build_config(arch_label: str, strategy_name: str) -> Dict[str, Any]:
    """Compose the full config dict for one ablation cell."""
    cfg = yaml.safe_load(yaml.dump(PROD_HYPERPARAMS))  # deep copy
    cfg["model"]["type"] = ARCHITECTURES[arch_label]
    cfg["masking"] = dict(MASKING_STRATEGIES[strategy_name])
    return cfg


def _render(arch_label: str, strategy_name: str) -> str:
    """Return the full YAML text for one cell, including the header."""
    cfg = _build_config(arch_label, strategy_name)
    header = HEADER_COMMENT.format(
        arch_label=arch_label,
        arch_class=ARCHITECTURES[arch_label],
        strategy_name=strategy_name,
    )
    return header + yaml.safe_dump(cfg, sort_keys=True, default_flow_style=False)


def _write_all(out_dir: Path) -> int:
    out_dir.mkdir(parents=True, exist_ok=True)
    n = 0
    for arch_label in ARCHITECTURES:
        for strategy_name in MASKING_STRATEGIES:
            filename = f"{arch_label}__{strategy_name}__case118.yaml"
            (out_dir / filename).write_text(_render(arch_label, strategy_name))
            n += 1
    return n


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    out_dir = repo_root / "examples" / "config" / "ablation_case118"
    n = _write_all(out_dir)
    print(f"Wrote {n} ablation configs to {out_dir.relative_to(repo_root)}/")


if __name__ == "__main__":
    main()
